### ISSUE TITLE
error when calling any delete http call

### ISSUE THREAD

**Issue by uwlnf** [AtriaStar/Atria#181]
response: 404 not found

**Comment by uwlnf** [comment]
does it work?

- wse: no
- question: no
- answer: no
- review: no
- collab: no

current progress: :(

**Comment by JohHub** [comment]
delete wse works for me

**Comment by JohHub** [comment]
Actually, deleting wse after api checks have been made seems to not work.

<details>
  <summary>Stacktrace</summary>
  
  ```c#
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Npgsql.PostgresException (0x80004005): 23503: Aktualisieren oder Löschen in Tabelle »webservice_entries« verletzt Fremdschlüssel-Constraint »fk_api_check_webservice_entries_webservice_entry_id« von Tabelle »api_check«

      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
        Exception data:
          Severity: FEHLER
          SqlState: 23503
          MessageText: Aktualisieren oder Löschen in Tabelle »webservice_entries« verletzt Fremdschlüssel-Constraint »fk_api_check_webservice_entries_webservice_entry_id« von Tabelle »api_check«
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          SchemaName: public
          TableName: api_check
          ConstraintName: fk_api_check_webservice_entries_webservice_entry_id
          File: ri_triggers.c
          Line: 2553
          Routine: ri_ReportViolation
         --- End of inner exception stack trace ---
 ```
</details>
